#ifndef UNDERSCORE_DIALECT_H
#define UNDERSCORE_DIALECT_H

#include "mlir/IR/Dialect.h"

// 1. Pull in the "Declarations" generated by TableGen
// This includes the class definition for UnderscoreDialect
#include "dialect/UnderscoreDialect.h.inc"

#endif // UNDERSCORE_DIALECT_H
